### ISSUE TITLE
一段简单的CSS3垂直居中代码

### ISSUE THREAD

**Issue by calidion** [calidion/calidion.github.io#12]
垂直居中代码网上有很多, 我今天也搜索了很久,发现了一个最简单的方案:
http://zerosixthree.se/vertical-align-anything-with-just-3-lines-of-css/

这个代码号称只要三行,实际上光三行代码是无法真正的起作用的.必须要有一个外面的wrapper来配合.
由于原文的内容比较多,我将内容精减一下,并制作了下面的实例.
http://codepen.io/calidion/pen/VapmBx

html:

``` html
<DOCTYPE html>
<html>
<body>
  <div class="fixed">
    <div class="vcenter-wrap">
      <div class="vcenter">
        content middle aligened
      </div>
    </div>
  </div>
</body>

</html>
```

CSS:

``` css
.fixed {
  position: fixed;
  top: 0;
  left: 0;
  right:0;
  bottom: 0;
  background-color: #fcc;
}

.vcenter-wrap {
  display: block;
/*   height: 100%; */ /*对于高度不固定的*/
  height: 100px;
}
.vcenter {
  position: relative;
  top: 50%;
  transform: translateY(-50%);
}
```

所以定义好之后,我们直接将如果下代码块放进任何一个需要居中的代码中都是可以成立的.

``` html
    <div class="vcenter-wrap">
      <div class="vcenter">
        居中的代码放这里
      </div>
    </div>
```

这段代码只在支持CSS3 tansform的浏览器里有效.
所以对于有些旧的浏览器是无效的, 需慎重使用.
对于移动Web来说,应该是使用起来是没有压力的,欢迎使用.
